CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    mfa_secret VARCHAR2(32) NOT NULL
);
SELECT id, email, password_hash, mfa_secret FROM users;
